version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: salon_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 051012
      POSTGRES_DB: salonbooking_db
    ports:
      - "5432:5432"
    volumes:
      - salon_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: salon_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@salon.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  salon_data:
